export const uiIcons = {
  back: { prefix: "solid", icon: "xmark" },
  expand: { prefix: "solid", icon: "up-right-and-down-left-from-center" },
  new: { prefix: "solid", icon: "plus" },
  edit: { prefix: "solid", icon: "pen-to-square" },
  delete: { prefix: "solid", icon: "trash" },
  home: { prefix: "solid", icon: "house" },
  show: { prefix: "solid", icon: "caret-down" },
  hide: { prefix: "solid", icon: "caret-up" },
  tag: { prefix: "solid", icon: "tag" },
  inbox: { prefix: "solid", icon: "inbox" },
  filter: { prefix: "solid", icon: "filter" },
  search: { prefix: "solid", icon: "magnifying-glass" },
  project: { prefix: "solid", icon: "hashtag" },
  note: { prefix: "regular", icon: "note-sticky" },
  projectList: { prefix: "solid", icon: "folder-tree" },
  todoList: { prefix: "solid", icon: "list-check" },
  noteList: { prefix: "regular", icon: "message" },
  imminence: { prefix: "solid", icon: "calendar-day" },
  dueDate: { prefix: "solid", icon: "calendar-day" },
  priority: { prefix: "solid", icon: "flag" },
  state: { prefix: "solid", icon: "circle-half-stroke" },
  settings: { prefix: "solid", icon: "sliders" },
  sortBy: { prefix: "solid", icon: "sort" },
  ascending: { prefix: "solid", icon: "arrow-down-short-wide" },
  descending: { prefix: "solid", icon: "arrow-up-short-wide" },
};
