export const uiIcons = {
  back: { prefix: "solid", icon: "xmark" },
  expand: { prefix: "solid", icon: "up-right-and-down-left-from-center" },
  new: { prefix: "solid", icon: "plus" },
  edit: { prefix: "solid", icon: "pen-to-square" },
  delete: { prefix: "solid", icon: "trash" },
  home: { prefix: "solid", icon: "house" },
  show: { prefix: "solid", icon: "caret-down" },
  hide: { prefix: "solid", icon: "caret-up" },
  tag: { prefix: "solid", icon: "tag" },
  filter: { prefix: "solid", icon: "filter" },
  search: { prefix: "solid", icon: "magnify-glass" },
  projectList: { prefix: "solid", icon: "hashtag" },
  todoList: { prefix: "solid", icon: "list-check" },
  noteList: { prefix: "regular", icon: "message" },
};
